### PR TITLE
Add support for ATOMIC-POP and ATOMIC-PUSH

### PR DESCRIPTION
**Pull request by hineios**
Add ATOMIC-POP and ATOMIC-PUSH.
Add unit tests for both.

### CODE REVIEW

**Comment by hineios** [comment]
Some of the currently supported CL implementations do not support theses operations natively, therefore I ommited them from the new operands.
Namely CCL, Clasp, and Mezzano.
Should I try and implement them for the missing implementations? 

As I am writting this, I realise I should update the documentation.
I'll get to it briefly.

**Comment by Shinmera** [comment]
I think atomic push and pop should be implementable using just CAS without any other implementation support being required, so adding a fallback would be good.

**Comment by hineios** [comment]
My shame has finally taken the best of me...

I've used ECL's implementation of atomic `pop` and `push` to implement the generic fallback you requested.

As for the documentation, do you have a generator or write it by hand.
I've found it quite cumbersome to write to that HTML file, but I have a version I can upload into this pull request.
Any notes on that?

**Comment by hineios** [comment]
Oh, and I rebased my pull request.

**Comment by Shinmera** [comment]
Documentation is written in the `documentation.lisp` file and generated from there.

As for the tests, please use Parachute's [``skip-on``](https://shinmera.github.io/parachute/#MACRO-FUNCTION%20PARACHUTE:SKIP-ON) feature to exclude implementations rather than using reader conditionals.

**Comment by hineios** [comment]
I've updated and generated the new documentation.

I'm not sure on restrictions, but I've made a reference to check `CAS` for restrictions.

And I figure that the reader conditionals on the tests are no longer necessary since we now have an implementation based on `CAS`.

FWIW, I've only tested in Allegro CL and SBCL on Windows. Not sure if that's relevant.

**Comment by Shinmera** [comment]
That's alright, as long as there are tests at all! :)

**Comment by Shinmera** [comment]
Thanks a lot for your work!

**Pull request merged**
